"""
Django settings for company_system project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g0)3d2e%+ning)1#8(sq*sea)_gs2ya%ee^g7-4atau5b1av#f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.95', 'edges-sat-nikon-presently.trycloudflare.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Third-party apps
    'tailwind',
    'theme',
    # AllAuth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Local apps
    'App.finance',
    'App.kpi',
    'App.sales',
    'App.marketing',
    'App.employees',
    'App.users',
    'App.authentication',
    'App.master_dashboard',
    'App.human_resource',
    'App.task_management',
]

# django-allauth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# New allauth settings (recommended)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' for email verification

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # django-allauth middleware
    'allauth.account.middleware.AccountMiddleware',
    # Custom middleware
    'App.authentication.middleware.IdleSessionTimeoutMiddleware',
]

ROOT_URLCONF = 'sub_company_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'App.authentication.context_processors.session_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'sub_company_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'company_db',        # same name you created in pgAdmin
        'USER': 'postgres',          # default PostgreSQL user
        'PASSWORD': 'Admin@123',  # password you set during install
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#_ZONE = 'UTC'

TIME_ZONE = 'Asia/Manila'  # for Philippines
USE_TZ = True

USE_I18N = True

USE_TZ = True

# Media files (uploaded files like payslips, loan docs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (Production)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
    os.path.join(BASE_DIR, 'theme', 'static'),
    os.path.join(BASE_DIR, 'node_modules'),
]

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/hr_dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Tailwind CSS Configuration
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = "npm.cmd"

# Owner/Developer Bypass Login Credentials
# IMPORTANT: Store hashed password in production!
OWNER_LOGIN_ID = "OWNER"
# Use environment variable in production: OWNER_PASSWORD_HASH
# Generate hash using: from django.contrib.auth.hashers import make_password; print(make_password('your-password'))
OWNER_PASSWORD_HASH = os.environ.get('OWNER_PASSWORD_HASH', 'pbkdf2_sha256$1000000$pwEDFjHGE9oNOBrvyjJuc1$SkSnGtqqWswjB+IS5TE+Sg9i/tO0UT4XkYp8D1QTTs0=')

# Session Security
SESSION_COOKIE_AGE = 3600  # 1 hour (in seconds)
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS from accessing cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Use session age, not browser close

# ====================================================================
# SESSION TIMEOUT SETTINGS (You edit these values)
# ====================================================================
# IDLE_SESSION_TIMEOUT: Total time (seconds) before auto-logout
#   - 60 = 1 minute (testing)
#   - 1800 = 30 minutes (production)
# IDLE_SESSION_TIMEOUT_WARNING: When to show warning banner
#   - 30 = Show warning 30 seconds before logout
#   - 300 = Show warning 5 minutes before logout
# ====================================================================

IDLE_SESSION_TIMEOUT = 7200  # Total timeout: 7200 seconds = 2 hours
IDLE_SESSION_TIMEOUT_WARNING = 300  # Warning shows when 5 minutes remaining

# ====================================================================
# RATE LIMITING SETTINGS (You edit these values)
# ====================================================================
# MAX_LOGIN_ATTEMPTS: Number of failed attempts before lockout
#   - 5 = Lock after 5 failed attempts
# LOCKOUT_DURATION: Time in seconds to lock the account
#   - 900 = 15 minutes
#   - 1800 = 30 minutes
# ====================================================================

MAX_LOGIN_ATTEMPTS = 5  # Lock after 5 failed attempts
LOCKOUT_DURATION = 900  # 15 minutes lockout

# CSRF Protection
CSRF_COOKIE_AGE = 3600  # 1 hour
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access (needed for some AJAX)
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'  # Custom header for API calls
CSRF_TRUSTED_ORIGINS = ['https://edges-sat-nikon-presently.trycloudflare.com']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
